app:
  title: GitLab Pipelines Dynamic Smoke
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    host: 0.0.0.0
  cors:
    origin: http://localhost:7007
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: backstage

auth:
  environment: development
  providers:
    guest:
      userEntityRef: user:development/guest
      ownershipEntityRefs:
        - user:development/guest
      dangerouslyAllowOutsideDevelopment: true

integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://${GITLAB_HOST}/api/v4

catalog:
  locations:
    - type: file
      target: ./catalog/sample.yaml
      rules:
        - allow: [Resource]

permission:
  enabled: false
